---
kind: pipeline
name: "@postclick/php-logger unit tests + SAST"
type: kubernetes
node_selector:
  component: ci-runners

steps:
  - name: coding style
    image: eu.gcr.io/postclick-live-1/php-test:master
    pull: always
    commands:
      - cd /drone/src/packages/php-logger
      - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader --classmap-authoritative
      - /home/www-data/vendor/bin/phpcs --standard=phpcs.xml.dist
    environment:
      DOCKER_REGISTRY_CREDENTIALS:
        from_secret: DOCKER_REGISTRY_CREDENTIALS
  - name: unit tests
    image: eu.gcr.io/postclick-live-1/php-test:master
    pull: always
    commands:
      - cd /drone/src/packages/php-logger
      - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader --classmap-authoritative
      - /home/www-data/vendor/bin/phpunit --testdox --coverage-clover /tmp/code-coverage/clover -c phpunit.xml.dist
    environment:
      DOCKER_REGISTRY_CREDENTIALS:
        from_secret: DOCKER_REGISTRY_CREDENTIALS
    volumes:
      - name: coverage
        path: /tmp/code-coverage/
  - name: scan Sonarqube - Master
    image: eu.gcr.io/postclick-live-1/drone-plugin-sonarqube-scanner:master
    settings:
      POSTCLICK_SONAR_LOGIN:
        from_secret: POSTCLICK_SONARQUBE_LOGIN_TOKEN
      project_name: php-logger
      project_path: packages/php-logger
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITLAB_NPM_TOKEN:
        from_secret: GITLAB_NPM_TOKEN
    volumes:
      - name: coverage
        path: /tmp/code-coverage/
trigger:
  branch:
    - master
  event:
    - pull_request
volumes:
  - name: coverage
    temp: {}

---
kind: pipeline
name: "@postclick/php-logger SAST - master"
type: kubernetes
node_selector:
  component: ci-runners
steps:
  - name: unit tests
    image: eu.gcr.io/postclick-live-1/php-test:master
    pull: always
    commands:
      - cd /drone/src/packages/php-logger
      - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader --classmap-authoritative
      - /home/www-data/vendor/bin/phpunit --testdox --coverage-clover /tmp/code-coverage/clover -c phpunit.xml.dist
    environment:
      DOCKER_REGISTRY_CREDENTIALS:
        from_secret: DOCKER_REGISTRY_CREDENTIALS
    volumes:
      - name: coverage
        path: /tmp/code-coverage/
  - name: check dependencies
    image: eu.gcr.io/postclick-live-1/drone-plugin-dependency-check:master
    pull: always
    settings:
      mode: scan
      db_host: drone-dependency-check-db-dev-postgresql.drone-dev.svc.cluster.local
      db_password:
        from_secret: DEPENDENCY_CHECK_DB_PASSWORD
      project_name: postclick-php-logger
      project_path: packages/php-logger
    volumes:
      - name: audit-output
        path: /tmp/sonarqube-audit/
  - name: scan Sonarqube - Master
    image: eu.gcr.io/postclick-live-1/drone-plugin-sonarqube-scanner
    settings:
      POSTCLICK_SONAR_LOGIN:
        from_secret: POSTCLICK_SONARQUBE_LOGIN_TOKEN
      project_name: php-logger
      project_path: packages/php-logger
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITLAB_NPM_TOKEN:
        from_secret: GITLAB_NPM_TOKEN
    depends_on:
      - unit tests
      - check dependencies
    volumes:
      - name: audit-output
        path: /tmp/sonarqube-audit/
      - name: coverage
        path: /tmp/code-coverage/
trigger:
  branch:
    - master
  cron:
    - sonarqube-php-logger
  event:
    - cron
volumes:
  - name: coverage
    temp: {}
  - name: audit-output
    temp: {}
